version: '3.8'


services:

  flow_scheduler:
    build: 
      context: ..
      dockerfile: ./flow_scheduler/Dockerfile
      args:
        FLOW_DIR: ${FLOW_DIR}
    image: flow_scheduler
    container_name: flow_scheduler
    command: python setup.py
    environment:
      # Prefect
      - PREFECT_API_URL=${PREFECT_API_URL}
      # MLflow
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    networks:
      - mlops


networks:
  mlops:
    external: true